export const ADVICE_TOPICS = [
  {
    id: "popup2",
    title: "Video Ideas",
    description: "How to find a good video idea.",
    image: "/Thumbnails/Video-Ideas.webp",
    imageSmall: "/Thumbnails/Video-Ideas-small.webp",
    search: "youtube tools experts services communities creators",
    accent: "#7c3aed",
  },
  {
    id: "popup3",
    title: "Branding",
    description: "How to brand your content.",
    image: "/Thumbnails/Branding.webp",
    imageSmall: "/Thumbnails/Branding-small.webp",
    search: "sponsors sponsorships millions fans",
    accent: "#7c3aed",
  },
  {
    id: "popup4",
    title: "Tools",
    description: "The best tools you will need to use.",
    image: "/Thumbnails/Tools.webp",
    imageSmall: "/Thumbnails/Tools-small.webp",
    search: "impressions views videos",
    accent: "#2563eb",
  },
  {
    id: "popup5",
    title: "Sponsorships",
    description: "How to get sponsors for your channel.",
    image: "/Thumbnails/Sponsorships.webp",
    imageSmall: "/Thumbnails/Sponsorships-small.webp",
    search: "progress channel growth stage",
    accent: "#7c3aed",
  },
  {
    id: "popup6",
    title: "Impressions",
    description: "How to get more impressions.",
    image: "/Thumbnails/Impressions.webp",
    imageSmall: "/Thumbnails/Impressions-small.webp",
    search: "advertising advertisements reach people",
    accent: "#dc2626",
  },
  {
    id: "popup7",
    title: "Retention",
    description: "How to get good retention.",
    image: "/Thumbnails/Retention.webp",
    imageSmall: "/Thumbnails/Retention-small.webp",
    search: "analytics thumbnail viewer duration performance",
    accent: "#dc2626",
  },
  {
    id: "popup8",
    title: "Thumbnails",
    description: "How to make a great thumbnail.",
    image: "/Thumbnails/Thumbnails.webp",
    imageSmall: "/Thumbnails/Thumbnails-small.webp",
    search: "thumbnail click through rate ctr design",
    accent: "#7c3aed",
  },
  {
    id: "popup9",
    title: "Introductions",
    description: "How to make a great intro.",
    image: "/Thumbnails/Introductions.webp",
    imageSmall: "/Thumbnails/Introductions-small.webp",
    search: "intro hook opening first seconds",
    accent: "#2563eb",
  },
  {
    id: "popup10",
    title: "Titles",
    description: "How to make a great title.",
    image: "/Thumbnails/Titles.webp",
    imageSmall: "/Thumbnails/Titles-small.webp",
    search: "title keywords seo clickbait",
    accent: "#7c3aed",
  },
  {
    id: "popup11",
    title: "Storytelling",
    description: "How to make a good story.",
    image: "/Thumbnails/Storytelling.webp",
    imageSmall: "/Thumbnails/Storytelling-small.webp",
    search: "story narrative script structure",
    accent: "#dc2626",
  },
  {
    id: "popup12",
    title: "Editing",
    description: "How to edit your videos well.",
    image: "/Thumbnails/Editing.webp",
    imageSmall: "/Thumbnails/Editing-small.webp",
    search: "editing cuts pacing transitions",
    accent: "#2563eb",
  },
  {
    id: "popup13",
    title: "Engagement",
    description: "How to get more engagement.",
    image: "/Thumbnails/Engagement.webp",
    imageSmall: "/Thumbnails/Engagement-small.webp",
    search: "comments likes community interaction",
    accent: "#7c3aed",
  },
  {
    id: "popup14",
    title: "Emotions",
    description: "How to connect emotionally with viewers.",
    image: "/Thumbnails/Emotions.webp",
    imageSmall: "/Thumbnails/Emotions-small.webp",
    search: "emotion feelings connection audience",
    accent: "#dc2626",
  },
  {
    id: "popup16",
    title: "Progress",
    description: "How to track and improve your channel progress.",
    image: "/Thumbnails/Progress.webp",
    imageSmall: "/Thumbnails/Progress-small.webp",
    search: "progress growth milestones analytics",
    accent: "#2563eb",
  },
  {
    id: "popup17",
    title: "Advertising",
    description: "How to advertise your content effectively.",
    image: "/Thumbnails/Advertising.webp",
    imageSmall: "/Thumbnails/Advertising-small.webp",
    search: "ads promotion marketing reach",
    accent: "#dc2626",
  },
];
